# Generated by Django 3.2 on 2023-07-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_pub', '0006_article_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='cover',
        ),
        migrations.AddField(
            model_name='staff',
            name='position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(default='https://www.spectraresearch.com/wp-content/uploads/2022/09/default-image.jpg'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='picture',
            field=models.URLField(default='https://www.spectraresearch.com/wp-content/uploads/2022/09/default-image.jpg'),
        ),
    ]
