# Generated by Django 4.2.3 on 2023-07-05 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_pub', '0007_auto_20230703_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
    ]
