# Generated by Django 4.2.3 on 2023-07-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_pub', '0010_delete_game_alter_comment_options_comment_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.URLField(default='https://www.spectraresearch.com/wp-content/uploads/2022/09/default-image.jpg'),
        ),
    ]
