# Generated by Django 4.2.3 on 2023-07-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_pub', '0011_remove_comment_parent_comment_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
