# Generated by Django 4.2.3 on 2023-07-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_pub', '0012_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='starred_articles',
            field=models.ManyToManyField(blank=True, related_name='starred_by', to='nexus_pub.article'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='picture',
            field=models.URLField(default='https://moonvillageassociation.org/wp-content/uploads/2018/06/default-profile-picture1-744x744.jpg'),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.URLField(default='https://moonvillageassociation.org/wp-content/uploads/2018/06/default-profile-picture1-744x744.jpg'),
        ),
    ]
