# Generated by Django 4.2.3 on 2023-07-15 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_pub', '0014_user_saved_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
