# Generated by Django 4.2.3 on 2023-07-26 02:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_pub', '0016_game_user_games_played_user_games_won'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wordle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('games_played', models.IntegerField(default=0)),
                ('games_won', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='games_played',
        ),
        migrations.RemoveField(
            model_name='user',
            name='games_won',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.AddField(
            model_name='wordle',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wordle_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
