# Generated by Django 4.2.3 on 2023-07-26 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nexus_pub', '0017_wordle_remove_user_games_played_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='points',
        ),
        migrations.DeleteModel(
            name='Wordle',
        ),
    ]
